version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notebook_api-db
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: notebook_api
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notebook_api_network

  app:
    build:
      dockerfile: Dockerfile
    container_name: notebook_api_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: notebook_api
      DB_USERNAME: root
      DB_PASSWORD: secret
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - notebook_api_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: notebook_api_nginx
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8888:80"
    networks:
      - notebook_api_network
    depends_on:
      - app

volumes:
  mysql-data:


networks:
  notebook_api_network:
